language: node_js
node_js:
  - "10"
branches:
  only:
    - master
install:
  - npm install
script:
  - npm run build
  - docker build -t $DOCKER_USER/covid-tracker .
  - docker tag $DOCKER_USER/covid-tracker $DOCKER_USER/covid-tracker:1
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker push $DOCKER_USER/covid-tracker
notifications:
  email:
    on_failure: change
    on_success: change
